
name: Build and deploy (master)
'on':
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: GIT checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: "mymilk-lab"
          service_account_key: ${{ secrets.SA_MYMILK_LAB_GCP }}
          export_default_credentials: true
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
      - name: terraform init
        run: terraform init
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SA_MYMILK_LAB_GCP }}
      - name: terraform plan
        run: terraform plan -var "project_id=mymilk-lab"
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SA_MYMILK_LAB_GCP }}
